<div class="space-y-6">
    <div class="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-6">
        <div class="flex">
            <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-purple-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
                </svg>
            </div>
            <div class="ml-3">
                <h3 class="text-sm font-medium text-purple-800">Scope 3: Other Indirect Emissions</h3>
                <div class="mt-2 text-sm text-purple-700">
                    <p>These are indirect emissions that occur in your value chain, both upstream and downstream of your organization.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Business Travel - Flights -->
        <div>
            <label for="business_travel_flights_km" class="block text-sm font-medium text-gray-700 mb-2">
                Business Travel - Flights (km)
                <span class="ml-1 text-gray-400 cursor-help" title="Total distance of business flights in kilometers">
                    <svg class="w-4 h-4 inline" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm7 4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                    </svg>
                </span>
            </label>
            <div class="relative">
                <input type="number" 
                       id="business_travel_flights_km" 
                       name="business_travel_flights_km" 
                       value="{{ old('business_travel_flights_km', $emissionSource->business_travel_flights_km) }}"
                       step="0.01"
                       min="0"
                       class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm @error('business_travel_flights_km') border-red-300 @enderror"
                       placeholder="0.00">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                    <span class="text-gray-500 sm:text-sm">km</span>
                </div>
            </div>
            @error('business_travel_flights_km')
                <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
            @enderror
        </div>

        <!-- Car Hire -->
        <div>
            <label for="car_hire_km" class="block text-sm font-medium text-gray-700 mb-2">
                Car Hire/Rental (km)
                <span class="ml-1 text-gray-400 cursor-help" title="Total distance of rented/hired vehicles">
                    <svg class="w-4 h-4 inline" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm7 4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                    </svg>
                </span>
            </label>
            <div class="relative">
                <input type="number" 
                       id="car_hire_km" 
                       name="car_hire_km" 
                       value="{{ old('car_hire_km', $emissionSource->car_hire_km) }}"
                       step="0.01"
                       min="0"
                       class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm @error('car_hire_km') border-red-300 @enderror"
                       placeholder="0.00">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                    <span class="text-gray-500 sm:text-sm">km</span>
                </div>
            </div>
            @error('car_hire_km')
                <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
            @enderror
        </div>

        <!-- Waste -->
        <div>
            <label for="waste_tonnes" class="block text-sm font-medium text-gray-700 mb-2">
                Waste Generated (tonnes)
                <span class="ml-1 text-gray-400 cursor-help" title="Total waste generated by your organization">
                    <svg class="w-4 h-4 inline" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm7 4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                    </svg>
                </span>
            </label>
            <div class="relative">
                <input type="number" 
                       id="waste_tonnes" 
                       name="waste_tonnes" 
                       value="{{ old('waste_tonnes', $emissionSource->waste_tonnes) }}"
                       step="0.01"
                       min="0"
                       class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm @error('waste_tonnes') border-red-300 @enderror"
                       placeholder="0.00">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                    <span class="text-gray-500 sm:text-sm">tonnes</span>
                </div>
            </div>
            @error('waste_tonnes')
                <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
            @enderror
        </div>

        <!-- Water -->
        <div>
            <label for="water_m3" class="block text-sm font-medium text-gray-700 mb-2">
                Water Consumption (m³)
                <span class="ml-1 text-gray-400 cursor-help" title="Total water consumed by your organization">
                    <svg class="w-4 h-4 inline" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm7 4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                    </svg>
                </span>
            </label>
            <div class="relative">
                <input type="number" 
                       id="water_m3" 
                       name="water_m3" 
                       value="{{ old('water_m3', $emissionSource->water_m3) }}"
                       step="0.01"
                       min="0"
                       class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm @error('water_m3') border-red-300 @enderror"
                       placeholder="0.00">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                    <span class="text-gray-500 sm:text-sm">m³</span>
                </div>
            </div>
            @error('water_m3')
                <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
            @enderror
        </div>

        <!-- Purchased Goods -->
        <div class="md:col-span-2">
            <label for="purchased_goods" class="block text-sm font-medium text-gray-700 mb-2">
                Purchased Goods & Services (kg CO₂e)
                <span class="ml-1 text-gray-400 cursor-help" title="Emissions from purchased goods and services">
                    <svg class="w-4 h-4 inline" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm7 4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                    </svg>
                </span>
            </label>
            <div class="relative">
                <input type="number" 
                       id="purchased_goods" 
                       name="purchased_goods" 
                       value="{{ old('purchased_goods', $emissionSource->purchased_goods) }}"
                       step="0.01"
                       min="0"
                       class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-emerald-500 focus:border-emerald-500 sm:text-sm @error('purchased_goods') border-red-300 @enderror"
                       placeholder="0.00">
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                    <span class="text-gray-500 sm:text-sm">kg CO₂e</span>
                </div>
            </div>
            @error('purchased_goods')
                <p class="mt-1 text-sm text-red-600">{{ $message }}</p>
            @enderror
        </div>
    </div>

    <!-- Information Box -->
    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
        <div class="flex">
            <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-blue-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                </svg>
            </div>
            <div class="ml-3">
                <h3 class="text-sm font-medium text-blue-800">Scope 3 Emissions</h3>
                <div class="mt-2 text-sm text-blue-700">
                    <p>Include indirect emissions from your value chain:</p>
                    <ul class="list-disc list-inside mt-2 space-y-1">
                        <li><strong>Business Travel:</strong> Flights, hotels, ground transportation</li>
                        <li><strong>Employee Commuting:</strong> Staff travel to/from work</li>
                        <li><strong>Waste:</strong> Generated by your operations</li>
                        <li><strong>Water:</strong> Consumption and treatment</li>
                        <li><strong>Purchased Goods:</strong> Raw materials, supplies, services</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <!-- UAE-Specific Tips -->
    <div class="bg-emerald-50 border border-emerald-200 rounded-lg p-4">
        <div class="flex">
            <div class="flex-shrink-0">
                <svg class="h-5 w-5 text-emerald-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                </svg>
            </div>
            <div class="ml-3">
                <h3 class="text-sm font-medium text-emerald-800">UAE-Specific Considerations</h3>
                <div class="mt-2 text-sm text-emerald-700">
                    <ul class="list-disc list-inside space-y-1">
                        <li><strong>Desalinated Water:</strong> UAE's water has higher emissions due to desalination</li>
                        <li><strong>Hot Climate:</strong> Higher cooling and refrigeration needs</li>
                        <li><strong>Import Dependencies:</strong> Most goods are imported, increasing transport emissions</li>
                        <li><strong>Waste Management:</strong> Consider landfill vs. recycling emissions</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
