<?php

/**
 * IFRS S2 disclosure section schemas (Phase 1).
 * Narrative sections stored in company_disclosures.content as JSON keyed by field name.
 */
return [
    'ifrs_s2' => [
        'sections' => [
            'governance' => [
                'title' => 'Climate Governance',
                'reference' => 'IFRS S2 §5–7',
                'description' => 'How governance bodies oversee climate-related risks, opportunities, and targets.',
                'fields' => [
                    'board_oversight_body' => ['label' => 'Board / committee responsible for climate oversight', 'type' => 'text', 'required' => true],
                    'board_climate_integration' => ['label' => 'How climate is integrated into strategy and decision-making', 'type' => 'textarea', 'required' => true],
                    'management_accountable_role' => ['label' => 'Management role accountable for climate', 'type' => 'text', 'required' => true],
                    'board_climate_expertise' => ['label' => 'Climate expertise on the board (Y/N and detail)', 'type' => 'textarea', 'required' => false],
                    'target_oversight' => ['label' => 'How the board oversees climate targets and progress', 'type' => 'textarea', 'required' => true],
                    'remuneration_linked' => ['label' => 'Are climate metrics linked to remuneration?', 'type' => 'textarea', 'required' => false],
                    'oversight_frequency' => ['label' => 'Frequency of board climate discussions', 'type' => 'select', 'options' => ['Quarterly', 'Bi-annually', 'Annually', 'Ad hoc'], 'required' => true],
                ],
            ],
            'strategy' => [
                'title' => 'Climate Strategy',
                'reference' => 'IFRS S2 §8–13',
                'description' => 'Effects of climate risks and opportunities on strategy, transition plan, and resilience.',
                'fields' => [
                    'risks_short_term' => ['label' => 'Climate risks — short term (0–1 years)', 'type' => 'textarea', 'required' => true],
                    'risks_medium_term' => ['label' => 'Climate risks — medium term (1–5 years)', 'type' => 'textarea', 'required' => true],
                    'risks_long_term' => ['label' => 'Climate risks — long term (5+ years)', 'type' => 'textarea', 'required' => true],
                    'opportunities_summary' => ['label' => 'Climate-related opportunities identified', 'type' => 'textarea', 'required' => false],
                    'business_model_impact' => ['label' => 'Effects on business model and value chain', 'type' => 'textarea', 'required' => true],
                    'financial_impact' => ['label' => 'Effects on financial position and cash flows', 'type' => 'textarea', 'required' => true],
                    'transition_plan_summary' => ['label' => 'Transition plan summary', 'type' => 'textarea', 'required' => true],
                    'transition_resources' => ['label' => 'Key actions and resources for transition', 'type' => 'textarea', 'required' => false],
                    'scenario_analysis_done' => ['label' => 'Scenario analysis undertaken?', 'type' => 'select', 'options' => ['Yes', 'No', 'Planned'], 'required' => true],
                    'scenarios_used' => ['label' => 'Scenarios used (e.g. 1.5°C, 2°C, 4°C)', 'type' => 'text', 'required' => false],
                    'resilience_assessment' => ['label' => 'Resilience assessment summary', 'type' => 'textarea', 'required' => false],
                ],
            ],
            'risk_management' => [
                'title' => 'Climate Risk Management',
                'reference' => 'IFRS S2 §14–17',
                'description' => 'Processes to identify, assess, and monitor climate-related risks.',
                'fields' => [
                    'identify_process' => ['label' => 'Process to identify climate risks', 'type' => 'textarea', 'required' => true],
                    'assess_process' => ['label' => 'Process to assess climate risks', 'type' => 'textarea', 'required' => true],
                    'prioritise_process' => ['label' => 'Process to prioritise climate risks', 'type' => 'textarea', 'required' => true],
                    'monitor_process' => ['label' => 'Process to monitor climate risks', 'type' => 'textarea', 'required' => true],
                    'erm_integration' => ['label' => 'Integration with enterprise risk management', 'type' => 'textarea', 'required' => true],
                ],
            ],
        ],
        'completeness_weights' => [
            'governance' => 20,
            'strategy' => 25,
            'risk_management' => 15,
            'climate_risks' => 15,
            'climate_opportunities' => 10,
            'reduction_targets' => 15,
        ],
    ],

    'ifrs_s1' => [
        'material_topics' => [
            'water' => ['label' => 'Water & effluents', 'gri' => 'GRI 303'],
            'biodiversity' => ['label' => 'Biodiversity & ecosystems', 'gri' => 'GRI 304'],
            'supply_chain' => ['label' => 'Supply chain & responsible sourcing', 'gri' => 'GRI 308 / 414'],
            'workforce' => ['label' => 'Workforce & human capital', 'gri' => 'GRI 401–404'],
            'health_safety' => ['label' => 'Occupational health & safety', 'gri' => 'GRI 403'],
            'anti_corruption' => ['label' => 'Anti-corruption & ethics', 'gri' => 'GRI 205'],
            'community' => ['label' => 'Community engagement', 'gri' => 'GRI 413'],
            'waste' => ['label' => 'Waste & circular economy', 'gri' => 'GRI 306'],
            'energy' => ['label' => 'Energy (beyond climate reporting)', 'gri' => 'GRI 302'],
            'climate' => ['label' => 'Climate (cross-reference IFRS S2)', 'gri' => 'IFRS S2 / GRI 305'],
        ],
        'sections' => [
            'governance' => [
                'title' => 'Sustainability Governance',
                'reference' => 'IFRS S1 §27–29',
                'description' => 'How governance bodies oversee sustainability-related risks, opportunities, and targets.',
                'fields' => [
                    'board_oversight_body' => ['label' => 'Board / committee responsible for sustainability oversight', 'type' => 'text', 'required' => true],
                    'sustainability_integration' => ['label' => 'How sustainability is integrated into strategy and decision-making', 'type' => 'textarea', 'required' => true],
                    'management_accountable_role' => ['label' => 'Management role accountable for sustainability', 'type' => 'text', 'required' => true],
                    'material_topics_oversight' => ['label' => 'How the board oversees material sustainability topics', 'type' => 'textarea', 'required' => true],
                    'remuneration_linked' => ['label' => 'Are sustainability metrics linked to remuneration?', 'type' => 'textarea', 'required' => false],
                    'oversight_frequency' => ['label' => 'Frequency of board sustainability discussions', 'type' => 'select', 'options' => ['Quarterly', 'Bi-annually', 'Annually', 'Ad hoc'], 'required' => true],
                    'climate_cross_reference' => ['label' => 'Cross-reference to IFRS S2 climate governance (summary or "see IFRS S2 report")', 'type' => 'textarea', 'required' => false],
                ],
            ],
            'strategy' => [
                'title' => 'Sustainability Strategy',
                'reference' => 'IFRS S1 §30–33',
                'description' => 'Effects of sustainability risks and opportunities on strategy and business model.',
                'fields' => [
                    'risks_short_term' => ['label' => 'Sustainability risks — short term (0–1 years)', 'type' => 'textarea', 'required' => true],
                    'risks_medium_term' => ['label' => 'Sustainability risks — medium term (1–5 years)', 'type' => 'textarea', 'required' => true],
                    'risks_long_term' => ['label' => 'Sustainability risks — long term (5+ years)', 'type' => 'textarea', 'required' => true],
                    'opportunities_summary' => ['label' => 'Sustainability-related opportunities identified', 'type' => 'textarea', 'required' => false],
                    'business_model_impact' => ['label' => 'Effects on business model and value chain', 'type' => 'textarea', 'required' => true],
                    'financial_impact' => ['label' => 'Effects on financial position and cash flows', 'type' => 'textarea', 'required' => true],
                    'resources_allocated' => ['label' => 'Key actions and resources for sustainability priorities', 'type' => 'textarea', 'required' => false],
                    'climate_cross_reference' => ['label' => 'Cross-reference to IFRS S2 climate strategy', 'type' => 'textarea', 'required' => false],
                ],
            ],
            'risk_management' => [
                'title' => 'Sustainability Risk Management',
                'reference' => 'IFRS S1 §34–36',
                'description' => 'Processes to identify, assess, and monitor sustainability-related risks.',
                'fields' => [
                    'identify_process' => ['label' => 'Process to identify sustainability risks', 'type' => 'textarea', 'required' => true],
                    'assess_process' => ['label' => 'Process to assess sustainability risks', 'type' => 'textarea', 'required' => true],
                    'prioritise_process' => ['label' => 'Process to prioritise sustainability risks', 'type' => 'textarea', 'required' => true],
                    'monitor_process' => ['label' => 'Process to monitor sustainability risks', 'type' => 'textarea', 'required' => true],
                    'erm_integration' => ['label' => 'Integration with enterprise risk management', 'type' => 'textarea', 'required' => true],
                    'material_topics_process' => ['label' => 'How material topics are determined and reviewed', 'type' => 'textarea', 'required' => true],
                ],
            ],
        ],
        'completeness_weights' => [
            'governance' => 20,
            'strategy' => 25,
            'risk_management' => 15,
            'material_topics' => 15,
            'sustainability_risks' => 25,
        ],
    ],

    'gri' => [
        'content_index' => [
            'GRI 2-1' => ['title' => 'Organizational details', 'section' => 'general', 'field' => 'org_name'],
            'GRI 2-2' => ['title' => 'Entities included in reporting', 'section' => 'general', 'field' => 'entities_included'],
            'GRI 2-6' => ['title' => 'Activities, value chain', 'section' => 'general', 'field' => 'activities_value_chain'],
            'GRI 2-9' => ['title' => 'Governance structure', 'section' => 'general', 'field' => 'governance_structure'],
            'GRI 2-12' => ['title' => 'Role of governance in sustainability', 'section' => 'general', 'field' => 'governance_sustainability_role'],
            'GRI 2-29' => ['title' => 'Stakeholder engagement', 'section' => 'general', 'field' => 'stakeholder_engagement'],
            'GRI 3-1' => ['title' => 'Material topics process', 'section' => 'material_topics_process', 'field' => 'process_description'],
            'GRI 3-2' => ['title' => 'List of material topics', 'source' => 'material_topics'],
            'GRI 302-1' => ['title' => 'Energy consumption', 'section' => 'energy', 'field' => 'total_energy_gj'],
            'GRI 303-3' => ['title' => 'Water withdrawal', 'section' => 'water', 'field' => 'withdrawal_total_m3'],
            'GRI 303-5' => ['title' => 'Water consumption', 'section' => 'water', 'field' => 'consumption_total_m3'],
            'GRI 305-1' => ['title' => 'Direct (Scope 1) GHG emissions', 'source' => 'gri_305', 'metric' => 'scope1'],
            'GRI 305-2' => ['title' => 'Energy indirect (Scope 2) GHG emissions', 'source' => 'gri_305', 'metric' => 'scope2'],
            'GRI 305-3' => ['title' => 'Other indirect (Scope 3) GHG emissions', 'source' => 'gri_305', 'metric' => 'scope3'],
            'GRI 306-3' => ['title' => 'Waste generated', 'section' => 'waste', 'field' => 'waste_total_tonnes'],
            'GRI 401-1' => ['title' => 'New employee hires and turnover', 'section' => 'social_hr', 'field' => 'employees_new_hires'],
            'GRI 404-1' => ['title' => 'Average training hours', 'section' => 'social_hr', 'field' => 'training_hours_avg'],
            'GRI 405-1' => ['title' => 'Diversity of governance bodies and employees', 'section' => 'diversity', 'field' => 'women_management_percent'],
        ],
        'sections' => [
            'material_topics_process' => [
                'title' => 'GRI 3 — Material Topics',
                'reference' => 'GRI 3',
                'description' => 'How material topics were determined and the list of material topics.',
                'fields' => [
                    'process_description' => ['label' => 'Process to determine material topics (GRI 3-1)', 'type' => 'textarea', 'required' => true],
                    'stakeholders_consulted' => ['label' => 'Stakeholders consulted', 'type' => 'textarea', 'required' => false],
                    'review_frequency' => ['label' => 'How often material topics are reviewed', 'type' => 'select', 'options' => ['Annually', 'Bi-annually', 'Every 3 years', 'Ad hoc'], 'required' => true],
                ],
            ],
            'general' => [
                'title' => 'GRI 2 — General Disclosures',
                'reference' => 'GRI 2',
                'description' => 'Organisation profile, governance, ethics, and stakeholder engagement.',
                'fields' => [
                    'org_name' => ['label' => 'Organisation name and legal form', 'type' => 'text', 'required' => true],
                    'entities_included' => ['label' => 'Entities included in sustainability reporting', 'type' => 'textarea', 'required' => true],
                    'activities_value_chain' => ['label' => 'Activities, brands, products, and services', 'type' => 'textarea', 'required' => true],
                    'governance_structure' => ['label' => 'Governance structure and committees', 'type' => 'textarea', 'required' => true],
                    'governance_sustainability_role' => ['label' => 'Role of governance in overseeing sustainability', 'type' => 'textarea', 'required' => true],
                    'ethics_compliance' => ['label' => 'Ethics, integrity, and compliance approach', 'type' => 'textarea', 'required' => false],
                    'stakeholder_engagement' => ['label' => 'Stakeholder engagement approach (GRI 2-29)', 'type' => 'textarea', 'required' => true],
                ],
            ],
            'energy' => [
                'title' => 'GRI 302 — Energy',
                'reference' => 'GRI 302',
                'description' => 'Energy consumption within the organisation.',
                'fields' => [
                    'total_energy_gj' => ['label' => 'Total energy consumption (GJ)', 'type' => 'number', 'required' => true],
                    'renewable_energy_gj' => ['label' => 'Renewable energy consumption (GJ)', 'type' => 'number', 'required' => false],
                    'renewable_percent' => ['label' => 'Renewable energy (%)', 'type' => 'number', 'required' => false],
                    'energy_intensity_value' => ['label' => 'Energy intensity value', 'type' => 'number', 'required' => false],
                    'energy_intensity_denominator' => ['label' => 'Intensity denominator (e.g. revenue AED, employees)', 'type' => 'text', 'required' => false],
                    'methodology_notes' => ['label' => 'Methodology and boundaries', 'type' => 'textarea', 'required' => false],
                ],
            ],
            'water' => [
                'title' => 'GRI 303 — Water',
                'reference' => 'GRI 303',
                'description' => 'Water withdrawal, discharge, and consumption.',
                'fields' => [
                    'withdrawal_total_m3' => ['label' => 'Total water withdrawal (m³) — GRI 303-3', 'type' => 'number', 'required' => true],
                    'withdrawal_surface_m3' => ['label' => 'Surface water (m³)', 'type' => 'number', 'required' => false],
                    'withdrawal_groundwater_m3' => ['label' => 'Groundwater (m³)', 'type' => 'number', 'required' => false],
                    'withdrawal_municipal_m3' => ['label' => 'Municipal / third-party (m³)', 'type' => 'number', 'required' => false],
                    'discharge_total_m3' => ['label' => 'Total water discharge (m³) — GRI 303-4', 'type' => 'number', 'required' => false],
                    'consumption_total_m3' => ['label' => 'Total water consumption (m³) — GRI 303-5', 'type' => 'number', 'required' => false],
                    'water_stressed_areas_notes' => ['label' => 'Water-stressed areas breakdown', 'type' => 'textarea', 'required' => false],
                ],
            ],
            'waste' => [
                'title' => 'GRI 306 — Waste',
                'reference' => 'GRI 306',
                'description' => 'Waste generation and disposal.',
                'fields' => [
                    'waste_hazardous_tonnes' => ['label' => 'Hazardous waste generated (tonnes)', 'type' => 'number', 'required' => false],
                    'waste_non_hazardous_tonnes' => ['label' => 'Non-hazardous waste generated (tonnes)', 'type' => 'number', 'required' => true],
                    'waste_total_tonnes' => ['label' => 'Total waste generated (tonnes) — GRI 306-3', 'type' => 'number', 'required' => false],
                    'waste_recycled_tonnes' => ['label' => 'Diverted — recycling (tonnes) — GRI 306-4', 'type' => 'number', 'required' => false],
                    'waste_reuse_tonnes' => ['label' => 'Diverted — reuse / composting (tonnes)', 'type' => 'number', 'required' => false],
                    'waste_landfill_tonnes' => ['label' => 'Directed to landfill (tonnes) — GRI 306-5', 'type' => 'number', 'required' => false],
                    'waste_incineration_tonnes' => ['label' => 'Directed to incineration (tonnes)', 'type' => 'number', 'required' => false],
                ],
            ],
            'social_hr' => [
                'title' => 'GRI 401–404 — Employment & Training',
                'reference' => 'GRI 401 / 404',
                'description' => 'Workforce metrics and training.',
                'fields' => [
                    'employees_total' => ['label' => 'Total employees (headcount)', 'type' => 'number', 'required' => true],
                    'employees_new_hires' => ['label' => 'New employee hires', 'type' => 'number', 'required' => false],
                    'employees_turnover_percent' => ['label' => 'Employee turnover (%)', 'type' => 'number', 'required' => false],
                    'training_hours_avg' => ['label' => 'Average training hours per employee — GRI 404-1', 'type' => 'number', 'required' => false],
                    'parental_leave_return_rate' => ['label' => 'Parental leave return rate (%)', 'type' => 'number', 'required' => false],
                    'benefits_summary' => ['label' => 'Benefits provided to full-time employees', 'type' => 'textarea', 'required' => false],
                ],
            ],
            'diversity' => [
                'title' => 'GRI 405 — Diversity',
                'reference' => 'GRI 405',
                'description' => 'Diversity of governance bodies and employees.',
                'fields' => [
                    'women_management_percent' => ['label' => 'Women in management (%) — GRI 405-1', 'type' => 'number', 'required' => true],
                    'women_workforce_percent' => ['label' => 'Women in total workforce (%)', 'type' => 'number', 'required' => false],
                    'board_diversity_notes' => ['label' => 'Board / governance body diversity', 'type' => 'textarea', 'required' => false],
                    'age_diversity_notes' => ['label' => 'Age group diversity (optional)', 'type' => 'textarea', 'required' => false],
                ],
            ],
        ],
        'completeness_weights' => [
            'material_topics' => 10,
            'material_topics_process' => 10,
            'general' => 15,
            'energy' => 10,
            'water' => 10,
            'waste' => 10,
            'social_hr' => 15,
            'diversity' => 10,
            'gri_305' => 10,
        ],
    ],
];
