<?php

/**
 * Phase E.2b — Additional ESG scorecard KPIs (Enterprise export only).
 *
 * Merged at runtime by EsgScorecardService::buildEnterprise().
 * Metric keys must NOT duplicate config('esg_scorecard.categories').
 */
return [
    'categories' => [
        'environment' => [
            'title' => 'Environmental Performance',
            'metrics' => [
                'scope_2_market_tco2e' => [
                    'label' => 'Scope 2 GHG emissions (market-based)',
                    'unit' => 'tCO₂e',
                    'source' => 'ghg',
                    'field' => 'scope2_market',
                    'decimals' => 4,
                ],
                'renewable_energy_gj' => [
                    'label' => 'Renewable energy consumption',
                    'unit' => 'GJ',
                    'source' => 'gri',
                    'section' => 'energy',
                    'field' => 'renewable_energy_gj',
                    'decimals' => 2,
                ],
                'energy_intensity' => [
                    'label' => 'Energy intensity',
                    'unit' => 'GJ per unit',
                    'source' => 'gri',
                    'section' => 'energy',
                    'field' => 'energy_intensity_value',
                    'decimals' => 2,
                ],
                'water_discharge_m3' => [
                    'label' => 'Water discharge (GRI 303-4)',
                    'unit' => 'm³',
                    'source' => 'gri',
                    'section' => 'water',
                    'field' => 'discharge_total_m3',
                    'decimals' => 2,
                ],
                'water_surface_m3' => [
                    'label' => 'Water withdrawal — surface',
                    'unit' => 'm³',
                    'source' => 'gri',
                    'section' => 'water',
                    'field' => 'withdrawal_surface_m3',
                    'decimals' => 2,
                ],
                'water_groundwater_m3' => [
                    'label' => 'Water withdrawal — groundwater',
                    'unit' => 'm³',
                    'source' => 'gri',
                    'section' => 'water',
                    'field' => 'withdrawal_groundwater_m3',
                    'decimals' => 2,
                ],
                'water_municipal_m3' => [
                    'label' => 'Water withdrawal — municipal',
                    'unit' => 'm³',
                    'source' => 'gri',
                    'section' => 'water',
                    'field' => 'withdrawal_municipal_m3',
                    'decimals' => 2,
                ],
                'waste_hazardous_tonnes' => [
                    'label' => 'Hazardous waste generated',
                    'unit' => 'tonnes',
                    'source' => 'gri',
                    'section' => 'waste',
                    'field' => 'waste_hazardous_tonnes',
                    'decimals' => 2,
                ],
                'waste_non_hazardous_tonnes' => [
                    'label' => 'Non-hazardous waste generated',
                    'unit' => 'tonnes',
                    'source' => 'gri',
                    'section' => 'waste',
                    'field' => 'waste_non_hazardous_tonnes',
                    'decimals' => 2,
                ],
                'waste_landfill_tonnes' => [
                    'label' => 'Waste to landfill',
                    'unit' => 'tonnes',
                    'source' => 'gri',
                    'section' => 'waste',
                    'field' => 'waste_landfill_tonnes',
                    'decimals' => 2,
                ],
                'waste_incineration_tonnes' => [
                    'label' => 'Waste to incineration',
                    'unit' => 'tonnes',
                    'source' => 'gri',
                    'section' => 'waste',
                    'field' => 'waste_incineration_tonnes',
                    'decimals' => 2,
                ],
                'waste_reuse_tonnes' => [
                    'label' => 'Waste diverted — reuse / composting',
                    'unit' => 'tonnes',
                    'source' => 'gri',
                    'section' => 'waste',
                    'field' => 'waste_reuse_tonnes',
                    'decimals' => 2,
                ],
                'ghg_intensity_revenue' => [
                    'label' => 'GHG intensity (per revenue unit)',
                    'unit' => 'tCO₂e / unit',
                    'source' => 'manual',
                    'decimals' => 4,
                ],
                'air_emissions_tonnes' => [
                    'label' => 'Significant air emissions (NOx/SOx/PM)',
                    'unit' => 'metric tonnes',
                    'source' => 'manual',
                    'decimals' => 2,
                ],
                'environmental_fines_aed' => [
                    'label' => 'Environmental fines and penalties',
                    'unit' => 'AED',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'spills_count' => [
                    'label' => 'Significant spills',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'scope3_cat3_fuel_energy' => [
                    'label' => 'Scope 3 Cat 3 fuel- and energy-related',
                    'unit' => 'tCO₂e',
                    'source' => 'manual',
                    'decimals' => 2,
                ],
                'scope3_cat6_travel' => [
                    'label' => 'Scope 3 Cat 6 business travel',
                    'unit' => 'tCO₂e',
                    'source' => 'manual',
                    'decimals' => 2,
                ],
                'iso14001_certified_sites' => [
                    'label' => 'Sites with ISO 14001 certification',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'energy_gj_from_activity' => [
                    'label' => 'Total energy from Quick Input activity (GRI 302-1 auto)',
                    'unit' => 'GJ',
                    'source' => 'energy_activity',
                    'decimals' => 2,
                ],
            ],
        ],
        'social' => [
            'title' => 'Social Performance',
            'metrics' => [
                'recordable_injuries' => [
                    'label' => 'Recordable work-related injuries',
                    'unit' => 'count',
                    'source' => 'gri',
                    'section' => 'health_safety',
                    'field' => 'recordable_injuries',
                    'decimals' => 0,
                ],
                'hours_worked' => [
                    'label' => 'Total hours worked',
                    'unit' => 'hours',
                    'source' => 'gri',
                    'section' => 'health_safety',
                    'field' => 'hours_worked',
                    'decimals' => 0,
                ],
                'fatalities_employees' => [
                    'label' => 'Fatalities — employees',
                    'unit' => 'count',
                    'source' => 'gri',
                    'section' => 'health_safety',
                    'field' => 'fatalities_employees',
                    'decimals' => 0,
                ],
                'fatalities_contractors' => [
                    'label' => 'Fatalities — contractors',
                    'unit' => 'count',
                    'source' => 'gri',
                    'section' => 'health_safety',
                    'field' => 'fatalities_contractors',
                    'decimals' => 0,
                ],
                'parental_leave_return_rate' => [
                    'label' => 'Parental leave return rate',
                    'unit' => '%',
                    'source' => 'gri',
                    'section' => 'social_hr',
                    'field' => 'parental_leave_return_rate',
                    'decimals' => 1,
                ],
                'community_investment_esg' => [
                    'label' => 'Community investment (UAE ESG report)',
                    'unit' => 'AED',
                    'source' => 'esg_report',
                    'section' => 'community_impact',
                    'field' => 'total_investment_aed',
                    'decimals' => 0,
                ],
                'community_beneficiaries' => [
                    'label' => 'Community beneficiaries reached',
                    'unit' => 'people',
                    'source' => 'esg_report',
                    'section' => 'community_impact',
                    'field' => 'beneficiaries_count',
                    'decimals' => 0,
                ],
                'stakeholder_engagements' => [
                    'label' => 'Stakeholder engagement records',
                    'unit' => 'count',
                    'source' => 'stakeholder_count',
                    'decimals' => 0,
                ],
                'employees_uae' => [
                    'label' => 'Employees — UAE',
                    'unit' => 'employees',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'employees_gcc' => [
                    'label' => 'Employees — GCC (ex-UAE)',
                    'unit' => 'employees',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'employees_other_regions' => [
                    'label' => 'Employees — other regions',
                    'unit' => 'employees',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'contractors_total' => [
                    'label' => 'Contractors / contingent workers',
                    'unit' => 'workers',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'men_workforce_percent' => [
                    'label' => 'Men in total workforce',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'employees_under_30_percent' => [
                    'label' => 'Employees under 30 years',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'employees_30_50_percent' => [
                    'label' => 'Employees 30–50 years',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'employees_over_50_percent' => [
                    'label' => 'Employees over 50 years',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'new_hires_women_percent' => [
                    'label' => 'Women among new hires',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'training_spend_aed' => [
                    'label' => 'Training and development spend',
                    'unit' => 'AED',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'volunteer_hours' => [
                    'label' => 'Employee volunteer hours',
                    'unit' => 'hours',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'absenteeism_rate' => [
                    'label' => 'Absenteeism rate',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'employee_engagement_score' => [
                    'label' => 'Employee engagement score',
                    'unit' => 'score',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
            ],
        ],
        'governance' => [
            'title' => 'Governance Performance',
            'metrics' => [
                'ethics_training_percent' => [
                    'label' => 'Employees receiving ethics training',
                    'unit' => '%',
                    'source' => 'gri',
                    'section' => 'governance_metrics',
                    'field' => 'ethics_training_percent',
                    'decimals' => 1,
                ],
                'suppliers_screened_env_percent' => [
                    'label' => 'New suppliers screened — environmental',
                    'unit' => '%',
                    'source' => 'gri',
                    'section' => 'supply_chain',
                    'field' => 'suppliers_screened_environmental_percent',
                    'decimals' => 1,
                ],
                'suppliers_screened_social_percent' => [
                    'label' => 'New suppliers screened — social',
                    'unit' => '%',
                    'source' => 'gri',
                    'section' => 'supply_chain',
                    'field' => 'suppliers_screened_social_percent',
                    'decimals' => 1,
                ],
                'scope3_cat1_spend_aed' => [
                    'label' => 'Scope 3 Cat 1 purchased goods spend',
                    'unit' => 'AED',
                    'source' => 'gri',
                    'section' => 'supply_chain',
                    'field' => 'scope3_cat1_spend_aed',
                    'decimals' => 0,
                ],
                'board_independent_percent' => [
                    'label' => 'Independent board members',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'board_meetings_count' => [
                    'label' => 'Board / governance meetings held',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'whistleblower_reports' => [
                    'label' => 'Whistleblower reports received',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'political_contributions_aed' => [
                    'label' => 'Political contributions',
                    'unit' => 'AED',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'human_rights_incidents' => [
                    'label' => 'Human rights incidents',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'data_privacy_training_percent' => [
                    'label' => 'Employees receiving data privacy training',
                    'unit' => '%',
                    'source' => 'manual',
                    'decimals' => 1,
                ],
                'sustainability_linked_finance_aed' => [
                    'label' => 'Sustainability-linked finance outstanding',
                    'unit' => 'AED',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'esg_targets_active' => [
                    'label' => 'Active ESG sustainability targets',
                    'unit' => 'count',
                    'source' => 'esg_target_count',
                    'decimals' => 0,
                ],
                'supplier_audits_env' => [
                    'label' => 'Supplier environmental audits',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'supplier_audits_social' => [
                    'label' => 'Supplier social audits',
                    'unit' => 'count',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
                'tax_transparency_disclosed' => [
                    'label' => 'Tax transparency disclosure (1=yes)',
                    'unit' => 'flag',
                    'source' => 'manual',
                    'decimals' => 0,
                ],
            ],
        ],
    ],
];
